// Runtime validation of everything the server receives from browsers.
import { z } from 'zod';
import { LIMITS, PASSWORD_MIN, ROOM_ID_RE, isAllowedImageUrl, isAllowedSiteUrl, isValidUsername } from './constants';
import { ROOM_KINDS } from './media';

export { ROOM_ID_RE };
/** Title keys: anime from AniList ("al:") or MyAnimeList ("mal:"), TMDB series ("tv:") or movies ("mv:"). */
export const ANIME_KEY_RE = /^(al|mal|tv|mv):\d{1,9}$/;
const KEY_PREFIXES: Record<string, string[]> = { anilist: ['al'], jikan: ['mal'], tmdb: ['tv', 'mv'] };

const hexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/);
const idStr = z.string().regex(/^[A-Za-z0-9_-]{1,32}$/);
const animeKey = z.string().regex(ANIME_KEY_RE);
const text = (max: number) => z.string().max(max);
const optText = (max: number) => z.string().max(max).nullable().default(null);
const optInt = (min: number, max: number) => z.number().int().min(min).max(max).nullable().default(null);

export const roomIdSchema = z.string().regex(ROOM_ID_RE);

export const animeMetaSchema = z
  .object({
    key: animeKey,
    source: z.enum(['anilist', 'jikan', 'tmdb']),
    sourceId: z.number().int().positive(),
    idMal: z.number().int().positive().nullable().default(null),
    title: z.string().trim().min(1).max(300),
    titleEnglish: optText(300),
    titleNative: optText(300),
    cover: z.string().max(600).refine(isAllowedImageUrl, 'cover host not allowed'),
    color: hexColor.nullable().default(null),
    banner: z.string().max(600).refine(isAllowedImageUrl, 'banner host not allowed').nullable().default(null),
    format: optText(20),
    status: optText(24),
    episodes: optInt(0, 100_000),
    year: optInt(1900, 2200),
    season: optText(10),
    genres: z.array(text(40)).max(20).default([]),
    score: z.number().min(0).max(100).nullable().default(null),
    studio: optText(120),
    synopsis: z.string().default('').transform((s) => s.slice(0, LIMITS.synopsis)),
    url: z.string().max(300).refine(isAllowedSiteUrl, 'url host not allowed').nullable().default(null),
  })
  .refine((a) => KEY_PREFIXES[a.source].some((prefix) => a.key === `${prefix}:${a.sourceId}`), 'key/source mismatch');

const tierSchema = z.object({
  id: idStr,
  label: z.string().trim().min(1).max(LIMITS.tierLabel),
  color: hexColor,
});

const memberFields = {
  name: z.string().trim().min(1).max(LIMITS.memberName),
  color: hexColor,
  avatar: z.string().max(16),
};

/** Ops a browser is allowed to send (member.join is generated by the server). */
export const clientOpSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('anime.add'),
    anime: animeMetaSchema,
    place: z.object({ board: idStr, to: idStr }).optional(),
  }),
  z.object({ type: z.literal('anime.remove'), key: animeKey }),
  z.object({
    type: z.literal('board.move'),
    board: idStr,
    key: animeKey,
    to: idStr,
    index: z.number().int().min(0).max(100_000),
  }),
  z.object({ type: z.literal('board.copy'), board: idStr, from: idStr }),
  z.object({ type: z.literal('board.clear'), board: idStr }),
  z.object({
    type: z.literal('review.set'),
    key: animeKey,
    patch: z
      .object({
        rating: z.number().int().min(1).max(10).nullable(),
        recommend: z.enum(['yes', 'maybe', 'no']).nullable(),
        status: z.enum(['watched', 'watching', 'plan', 'dropped']).nullable(),
        opinion: z.string().max(LIMITS.opinion),
      })
      .partial(),
  }),
  z.object({ type: z.literal('tiers.set'), tiers: z.array(tierSchema).min(1).max(LIMITS.maxTiers) }),
  z.object({ type: z.literal('room.rename'), name: z.string().trim().min(1).max(LIMITS.roomName) }),
  z.object({ type: z.literal('member.update'), ...memberFields }),
  z.object({ type: z.literal('chat.send'), id: idStr, text: z.string().trim().min(1).max(LIMITS.chatText) }),
]);

export const opMessageSchema = z.object({
  cid: idStr,
  op: clientOpSchema,
});

// --- Accounts ------------------------------------------------------------------

export const usernameSchema = z.string().trim().toLowerCase().refine(isValidUsername, 'invalid_username');
export const passwordSchema = z.string().min(PASSWORD_MIN).max(128);
const userIdSchema = z.string().regex(/^[A-Za-z0-9_-]{8,32}$/);
const userSecretSchema = z.string().regex(/^[A-Za-z0-9_-]{16,64}$/);

export const registerSchema = z
  .object({
    username: usernameSchema,
    password: passwordSchema,
    ...memberFields,
    // The identity already used in rooms, so the account keeps it (optional)…
    id: userIdSchema.optional(),
    secret: userSecretSchema.optional(),
    // …and the rooms this browser has been in with it, to start "As tuas salas".
    rooms: z
      .array(z.object({ id: roomIdSchema, visitedAt: z.number().int().min(0) }))
      .max(50)
      .optional(),
  })
  .refine((d) => !!d.id === !!d.secret, 'id and secret go together');

export const loginSchema = z.object({ username: usernameSchema, password: z.string().min(1).max(128) });
export const profileSchema = z.object(memberFields);
export const passwordChangeSchema = z.object({ current: z.string().min(1).max(128), next: passwordSchema });

export const joinSchema = z.object({
  roomId: roomIdSchema,
  user: z.object({
    id: userIdSchema,
    secret: z.string().min(16).max(64),
    ...memberFields,
  }),
  /** Username of the account this identity belongs to (to remember the room in "As tuas salas"). */
  account: usernameSchema.optional().catch(undefined),
});

const nullableKeyOrChat = z.union([animeKey, z.literal('chat')]).nullable();

export const presencePatchSchema = z
  .object({
    tab: z.enum(['tierlist', 'explore', 'ranking', 'members', 'chat']).nullable(),
    board: idStr.nullable(),
    viewing: animeKey.nullable(),
    typing: nullableKeyOrChat,
    dragging: z
      .object({
        key: animeKey,
        over: idStr.nullable(),
        index: z.number().int().min(0).max(100_000).nullable(),
      })
      .nullable(),
  })
  .partial();

export const cursorSchema = z
  .object({
    board: idStr,
    zone: idStr,
    fx: z.number().min(0).max(1),
    fy: z.number().min(0).max(1),
  })
  .nullable();

export const createRoomSchema = z.object({
  name: z.string().trim().min(1).max(LIMITS.roomName),
  kind: z.enum(ROOM_KINDS).default('anime'),
});
