// Runtime validation of everything the server receives from browsers.
import { z } from 'zod';
import { LIMITS, isAllowedImageUrl, isAllowedSiteUrl } from './constants';

export const ROOM_ID_RE = /^[a-z0-9]{6,16}$/;
export const ANIME_KEY_RE = /^(al|mal):\d{1,9}$/;

const hexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/);
const idStr = z.string().regex(/^[A-Za-z0-9_-]{1,32}$/);
const animeKey = z.string().regex(ANIME_KEY_RE);
const text = (max: number) => z.string().max(max);
const optText = (max: number) => z.string().max(max).nullable().default(null);
const optInt = (min: number, max: number) => z.number().int().min(min).max(max).nullable().default(null);

export const roomIdSchema = z.string().regex(ROOM_ID_RE);

export const animeMetaSchema = z
  .object({
    key: animeKey,
    source: z.enum(['anilist', 'jikan']),
    sourceId: z.number().int().positive(),
    idMal: z.number().int().positive().nullable().default(null),
    title: z.string().trim().min(1).max(300),
    titleEnglish: optText(300),
    titleNative: optText(300),
    cover: z.string().max(600).refine(isAllowedImageUrl, 'cover host not allowed'),
    color: hexColor.nullable().default(null),
    banner: z.string().max(600).refine(isAllowedImageUrl, 'banner host not allowed').nullable().default(null),
    format: optText(20),
    status: optText(24),
    episodes: optInt(0, 100_000),
    year: optInt(1900, 2200),
    season: optText(10),
    genres: z.array(text(40)).max(20).default([]),
    score: z.number().min(0).max(100).nullable().default(null),
    studio: optText(120),
    synopsis: z.string().default('').transform((s) => s.slice(0, LIMITS.synopsis)),
    url: z.string().max(300).refine(isAllowedSiteUrl, 'url host not allowed').nullable().default(null),
  })
  .refine((a) => a.key === `${a.source === 'anilist' ? 'al' : 'mal'}:${a.sourceId}`, 'key/source mismatch');

const tierSchema = z.object({
  id: idStr,
  label: z.string().trim().min(1).max(LIMITS.tierLabel),
  color: hexColor,
});

const memberFields = {
  name: z.string().trim().min(1).max(LIMITS.memberName),
  color: hexColor,
  avatar: z.string().max(16),
};

/** Ops a browser is allowed to send (member.join is generated by the server). */
export const clientOpSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('anime.add'),
    anime: animeMetaSchema,
    place: z.object({ board: idStr, to: idStr }).optional(),
  }),
  z.object({ type: z.literal('anime.remove'), key: animeKey }),
  z.object({
    type: z.literal('board.move'),
    board: idStr,
    key: animeKey,
    to: idStr,
    index: z.number().int().min(0).max(100_000),
  }),
  z.object({ type: z.literal('board.copy'), board: idStr, from: idStr }),
  z.object({ type: z.literal('board.clear'), board: idStr }),
  z.object({
    type: z.literal('review.set'),
    key: animeKey,
    patch: z
      .object({
        rating: z.number().int().min(1).max(10).nullable(),
        recommend: z.enum(['yes', 'maybe', 'no']).nullable(),
        status: z.enum(['watched', 'watching', 'plan', 'dropped']).nullable(),
        opinion: z.string().max(LIMITS.opinion),
      })
      .partial(),
  }),
  z.object({ type: z.literal('tiers.set'), tiers: z.array(tierSchema).min(1).max(LIMITS.maxTiers) }),
  z.object({ type: z.literal('room.rename'), name: z.string().trim().min(1).max(LIMITS.roomName) }),
  z.object({ type: z.literal('member.update'), ...memberFields }),
  z.object({ type: z.literal('chat.send'), id: idStr, text: z.string().trim().min(1).max(LIMITS.chatText) }),
]);

export const opMessageSchema = z.object({
  cid: idStr,
  op: clientOpSchema,
});

export const joinSchema = z.object({
  roomId: roomIdSchema,
  user: z.object({
    id: z.string().regex(/^[A-Za-z0-9_-]{8,32}$/),
    secret: z.string().min(16).max(64),
    ...memberFields,
  }),
});

const nullableKeyOrChat = z.union([animeKey, z.literal('chat')]).nullable();

export const presencePatchSchema = z
  .object({
    tab: z.enum(['tierlist', 'explore', 'ranking', 'members', 'chat']).nullable(),
    board: idStr.nullable(),
    viewing: animeKey.nullable(),
    typing: nullableKeyOrChat,
    dragging: z
      .object({
        key: animeKey,
        over: idStr.nullable(),
        index: z.number().int().min(0).max(100_000).nullable(),
      })
      .nullable(),
  })
  .partial();

export const cursorSchema = z
  .object({
    board: idStr,
    zone: idStr,
    fx: z.number().min(0).max(1),
    fy: z.number().min(0).max(1),
  })
  .nullable();

export const createRoomSchema = z.object({
  name: z.string().trim().min(1).max(LIMITS.roomName),
});
